{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "lists-viewer.fullname" . }}
  labels:
    {{- include "lists-viewer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingress.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`){{- if .path }} && PathPrefix(`{{ .path }}`){{- end }}
      kind: Rule
      services:
        - name: {{ include "lists-viewer.fullname" $ }}
          port: {{ $.Values.service.port }}
      {{- if $.Values.ingress.middlewares }}
      middlewares:
        {{- range $.Values.ingress.middlewares }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- if .Values.ingress.tls.certResolver }}
    certResolver: {{ .Values.ingress.tls.certResolver }}
    {{- end }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
    {{- if .Values.ingress.tls.domains }}
    domains:
      {{- range .Values.ingress.tls.domains }}
      - main: {{ .main }}
        {{- if .sans }}
        sans:
          {{- range .sans }}
          - {{ . }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
