apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lists-viewer.fullname" . }}-mongodb
  labels:
    {{- include "lists-viewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  uri: {{ .Values.mongodb.uri | quote }}
